import os
import subprocess
import sys

from setuptools import setup, find_packages

with open('README.rst') as readme:
    long_description = readme.read()

extra_packages = []
if sys.version_info[0] == 2 and sys.version_info[1] == 6:
    extra_packages = ['argparse']

version_py = os.path.join(os.path.dirname(__file__), 'cmdchk', 'version.py')

try:
    version_git = subprocess.check_output(['/usr/bin/git', 'describe']).rstrip()[1:]
except (OSError, subprocess.CalledProcessError):
    with open(version_py) as f:
        version_git = f.read().strip().split(' = ')[-1].replace("'", '')

version_msg = '# Generated by setup.py from git tag.'
with open(version_py, 'w') as f:
    f.write(version_msg + "\n__version__ = '" + version_git + "'\n")

setup(
    name='cmdchk',
    version=version_git,
    description='A monitoring program that responds over HTTP.',
    long_description=long_description,
    url='http://git.launchbrigade.com/emarks/cmdchk',
    author='Ellison Marks',
    author_email='emarks@scratchspace.com',
    license='NCSA',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: System Administrators',
        'License :: OSI Approved :: University of Illinois/NCSA Open Source License',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: System :: Monitoring',
    ],
    keywords='cluster monitor http',
    packages=find_packages(),
    install_requires=['setproctitle'].extend(extra_packages),
    platforms=['GNU/Linux'],
    entry_points={
        'console_scripts': [
            'cmdchk_wrapper = cmdchk:wrapper',
            'cmdchk_server = cmdchk:run_server',
        ]
    },
)
